export const Store: string[] = [
  'Amp Digital',
  'AMP101',
  'AMPTech',
  'Apoio Aguiar',
  'Apoio Aguiar Iniciante',
  'Apoio Aguiar Iniciantes',
  'Apoio M',
  'Apoio Vieira',
  'Assistente Aguiar',
  'Atibaia',
  'Auditoria',
  'Back Site',
  'Berlin',
  'Braganca I',
  'Braganca II',
  'Cacapava',
  'Cadastro',
  'Campinas',
  'Campinas II',
  'Caraguatatuba',
  'Carapicuiba',
  'CARIJOS F1',
  'Diadema',
  'Dona Benta',
  'Esteira',
  'Esteira Aguiar',
  'Esteira AMP101',
  'Esteira Vieira adm',
  'Ferraz I',
  'Ferraz II',
  'Ferraz III',
  'Fincanceiro',
  'Fortaleza',
  'Franco',
  'Franco II',
  'Franquias',
  'Gerente AMP101',
  'Gerente Esteira',
  'Gerente Red',
  'Gerente Refin',
  'Gerente Site',
  'Grimaldi',
  'Grimaldi II',
  'Guaianazes',
  'Guarulhos I',
  'Guarulhos II',
  'Helpdesk',
  'Helpdesk Aguiar',
  'Home Vieira',
  'Hortolandia',
  'Itaim',
  'Itapevi I',
  'Itapevi II',
  'Itaqua',
  'Jacarei I',
  'Jacarei II',
  'Jandira',
  'Jundiai I',
  'Jundiai II',
  'Mairipora',
  'Manutencao Aguiar',
  'Maua I',
  'Maua II',
  'Maua III',
  'Mogi das Cruzes',
  'Monitoramento',
  'Osasco',
  'Passagem',
  'Penha',
  'Pimentas',
  'Pinda',
  'Poa',
  'Quitanda',
  'Regiao',
  'Regiao Aguiar',
  'Retencao Aguiar',
  'Ribeirao Pires',
  'Ribeirao Pires 2',
  'Rio Grande da Serra I',
  'Rio Grande da Serra II',
  'Santo Amaro',
  'Santo Andre I',
  'Santo Andre II',
  'Santo Andre III',
  'Santo Andre IV',
  'Santos',
  'Sao Bento',
  'Sao Bernardo do Campo',
  'Sao Bernardo do Campo II',
  'Sao Jose',
  'Sao Mateus',
  'Sao Miguel I',
  'Sao Miguel II',
  'Sarandi',
  'Selecao',
  'Selecao Aguiar',
  'Site',
  'Socios',
  'Spark',
  'Sumare',
  'Suzano',
  'Suzano 2',
  'Taubate',
  'Taubate 2',
  'teste',
  'TI',
  'Treinamento AGU',
  'Treinamento AMP',
  'Vila Nova Cachoerinha'
]